# Generated by Django 6.0.6 on 2026-07-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllTransaction',
            fields=[
                ('date_sk', models.IntegerField(db_column='datesk', primary_key=True, serialize=False)),
                ('calendar_date', models.CharField(db_column='calendardate', max_length=10)),
                ('account_type', models.TextField(db_column='accounttype')),
                ('transaction_amount', models.FloatField(db_column='transactionamount')),
                ('balance', models.FloatField(db_column='balance', null=True)),
                ('label', models.TextField(db_column='label', null=True)),
                ('category_sk', models.IntegerField(db_column='categorysk', null=True)),
            ],
            options={
                'db_table': 'gold_Golden1_AllTransactions',
                'ordering': ['-date_sk'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UncategorizedTransaction',
            fields=[
                ('date_sk', models.IntegerField(db_column='datesk', primary_key=True, serialize=False)),
                ('account_type', models.TextField(db_column='accounttype')),
                ('calendar_date', models.CharField(db_column='calendardate', max_length=10)),
                ('transaction_description', models.TextField(db_column='transactiondescription')),
                ('transaction_amount', models.FloatField(db_column='transactionamount')),
            ],
            options={
                'db_table': 'gold_Golden1_UncategorizedTransactions',
                'ordering': ['-date_sk'],
                'managed': False,
            },
        ),
    ]
