# Generated by Django 6.0.6 on 2026-07-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('date_sk', models.IntegerField(db_column='datesk', primary_key=True, serialize=False)),
                ('calendar_date', models.CharField(db_column='calendardate', max_length=10)),
                ('credit_card_transaction_total', models.FloatField(db_column='creditcardtransactiontotal', null=True)),
                ('credit_card_balance', models.FloatField(db_column='creditcardbalance', null=True)),
                ('free_checking_transaction_total', models.FloatField(db_column='freecheckingtransactiontotal', null=True)),
                ('free_checking_balance', models.FloatField(db_column='freecheckingbalance', null=True)),
                ('money_market_transaction_total', models.FloatField(db_column='moneymarkettransactiontotal', null=True)),
                ('money_market_balance', models.FloatField(db_column='moneymarketbalance', null=True)),
                ('savings_transaction_total', models.FloatField(db_column='savingstransactiontotal', null=True)),
                ('savings_balance', models.FloatField(db_column='savingsbalance', null=True)),
                ('transaction_total', models.FloatField(db_column='transactiontotal', null=True)),
                ('total_balance', models.FloatField(db_column='totalbalance', null=True)),
                ('no_transactions_flag', models.IntegerField(db_column='notransactionsflag', null=True)),
            ],
            options={
                'db_table': 'gold_Golden1_DailyMetrics',
                'ordering': ['date_sk'],
                'managed': False,
            },
        ),
    ]
