# Generated by Django 6.0.6 on 2026-07-13 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAccess',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('app_id', models.CharField(max_length=100)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                (
                    'granted_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='app_access',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'app accesses',
                'ordering': ['user_id', 'app_id'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('user', 'app_id'), name='unique_app_access_per_user'
                    )
                ],
            },
        ),
    ]
