# Generated by Django 6.0.6 on 2026-07-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BudgetMap',
            fields=[
                (
                    'category_sk',
                    models.IntegerField(db_column='categorysk', primary_key=True, serialize=False),
                ),
                ('category', models.TextField(db_column='category')),
                ('category_budget', models.FloatField(db_column='categorybudget', null=True)),
                ('sub_category', models.TextField(db_column='subcategory')),
                (
                    'sub_category_budget',
                    models.FloatField(db_column='subcategorybudget', null=True),
                ),
            ],
            options={
                'db_table': 'gold_Golden1_BudgetMap',
                'ordering': ['category', 'sub_category'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetMapDocument',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('bank', models.CharField(max_length=100, unique=True)),
                ('yaml_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
