# Generated by Django 6.0.6 on 2026-07-21 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErdLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100)),
                ('namespace', models.CharField(max_length=200)),
                ('positions', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erd_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'omnierd_erdlayout',
                'ordering': ['user_id', 'source_id', 'namespace'],
                'constraints': [models.UniqueConstraint(fields=('user', 'source_id', 'namespace'), name='unique_erd_layout')],
            },
        ),
    ]
