# Generated by Django 6.0.6 on 2026-07-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni_erd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erdlayout',
            name='view_state',
            field=models.JSONField(default=dict),
        ),
    ]
