# Generated by Django 6.0.6 on 2026-07-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='RawFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('bank', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['bank', 'account', 'filename'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('bank', 'account', 'filename'), name='unique_rawfile_per_account'
                    )
                ],
            },
        ),
    ]
