# Generated by Django 6.0.6 on 2026-07-14 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rawdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rawfile',
            table='rawdata_rawfile',
        ),
    ]
